spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ielts_ascent_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true
