package com.ieltsascent.backend.domain.readingtest.enums;

public enum ReadingQuestionKind {
    MULTIPLE_CHOICE,
    TRUE_FALSE_NOT_GIVEN,
    YES_NO_NOT_GIVEN,
    MATCHING_HEADINGS,
    MATCHING_INFORMATION,
    MATCHING_SENTENCE_ENDINGS,
    MATCHING_FEATURES,
    SHORT_ANSWER,
    SENTENCE_COMPLETION,
    SUMMARY_COMPLETION,
    DIAGRAM_COMPLETION,
    FLOWCHART_COMPLETION,
    TABLE_COMPLETION
}